#!/usr/bin/env node

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

// Write via a wx temp file + renameSync so a symlink at the destination is
// replaced, never followed, and an interrupted run cannot leave a half-written
// report. Same pattern as atomicWriteFileSync in bin/akili.js.
function atomicWriteFileSync(targetPath, data) {
  const tmpPath = targetPath + "." + crypto.randomBytes(6).toString("hex") + ".tmp";
  try {
    fs.writeFileSync(tmpPath, data, { flag: "wx" });
    fs.renameSync(tmpPath, targetPath);
  } finally {
    try { fs.rmSync(tmpPath, { force: true }); } catch (e) {}
  }
}

function printHelp() {
  console.log(`AKILI Test Report Parser

Usage:
  node parse_tests.js <input-results.json> [output-report.md]

Arguments:
  input-results.json  JSON output file generated by Jest/Vitest (using --json option)
  output-report.md    Optional path to write/append the markdown report (defaults to stdout)
`);
}

function parseTestJson(inputPath) {
  if (!fs.existsSync(inputPath)) {
    console.error(`ERROR: Input file not found: ${inputPath}`);
    process.exit(1);
  }

  let data;
  try {
    const raw = fs.readFileSync(inputPath, "utf8");
    data = JSON.parse(raw);
  } catch (e) {
    console.error(`ERROR: Failed to parse JSON: ${e.message}`);
    process.exit(1);
  }

  // extract overall metrics
  const total = data.numTotalTests || 0;
  const passed = data.numPassedTests || 0;
  const failed = data.numFailedTests || 0;
  const pending = data.numPendingTests || 0;
  const suites = data.numTotalTestSuites || 0;

  let markdown = `## Test Summary

- **Total Test Suites:** ${suites}
- **Total Test Cases:** ${total}
- **Passed:** ${passed}
- **Failed:** ${failed}
- **Skipped/Pending:** ${pending}

### Detailed Traceability Matrix

| Test Suite / File | Test Case | Status | Duration | Notes / Failure Messages |
| :--- | :--- | :--- | :--- | :--- |
`;

  const results = data.testResults || [];
  for (const suite of results) {
    const relativeSuitePath = path.relative(process.cwd(), suite.name || "unknown");
    const assertions = suite.assertionResults || [];

    if (assertions.length === 0 && suite.message) {
      // Suite-level failure or initialization failure
      markdown += `| \`${relativeSuitePath}\` | *Suite Failure* | 🔴 **FAILED** | - | \`${suite.message.replace(/\r?\n/g, " ").substring(0, 100)}...\` |\n`;
      continue;
    }

    for (const test of assertions) {
      const fullTitle = [...(test.ancestorTitles || []), test.title].join(" > ");
      let statusIndicator = "⚪ **PENDING**";
      if (test.status === "passed") {
        statusIndicator = "🟢 **PASSED**";
      } else if (test.status === "failed") {
        statusIndicator = "🔴 **FAILED**";
      }

      const duration = test.duration ? `${test.duration}ms` : "-";
      let failureNotes = "-";
      if (test.failureMessages && test.failureMessages.length > 0) {
        // Strip ANSI escape codes and clean up message.
        // Bound the input BEFORE the regex: only ~120 visible chars survive, and
        // multi-MB messages exhaust the regex engine backtrack stack (RangeError)
        // regardless of pattern shape. 2000 chars leaves ample room for ANSI codes.
        failureNotes = test.failureMessages[0]
          .slice(0, 2000)
          .replace(/[\u001B\u009B][[\]()#;?]*(?:(?:(?:(?:;[-a-zA-Z\d\/#&.:=?%@~_]+)*|[a-zA-Z\d]+(?:;[-a-zA-Z\d\/#&.:=?%@~_]*)*)?\u0007)|(?:(?:\d{1,4}(?:;\d{0,4})*)?[\dA-PR-TZcf-nq-uy=><~]))/g, "")
          .replace(/\r?\n/g, " ")
          .substring(0, 120);
        failureNotes = `\`${failureNotes}...\``;
      }

      markdown += `| \`${relativeSuitePath}\` | ${fullTitle} | ${statusIndicator} | ${duration} | ${failureNotes} |\n`;
    }
  }

  return markdown;
}

function main() {
  const args = process.argv.slice(2);
  if (args.length === 0 || args.includes("--help") || args.includes("-h")) {
    printHelp();
    process.exit(0);
  }

  const inputPath = args[0];
  const outputPath = args[1];

  const parsedMarkdown = parseTestJson(inputPath);

  if (outputPath) {
    atomicWriteFileSync(outputPath, parsedMarkdown);
    console.log(`Successfully generated markdown report at: ${outputPath}`);
  } else {
    console.log(parsedMarkdown);
  }
}

main();
